---
name: "GHA Lint Job"
description: "Run linting on a project repository."

inputs:
  go-version:
    default: "1.16"
    description: "The version of golang to install."
    required: false
  packer-version:
    description: "The version of Packer to install."
    required: true
  python-version:
    default: "3.9"
    description: "The version of Python to install."
    required: false
  run-tmate:
    description: "Flag whether or not to set up a tmate session."
    required: true
  terraform-version:
    description: "The version of Terraform to install."
    required: true
